config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get '/users/sign_out'=>'devise/sessions#destroy'
  end
  resources :posts do
    resources :comments
  end
  root 'posts#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post

    return unless user.present?  # additional permissions for logged in users (they can read their own posts)
    can :manage, Post, user: user
    can :manage, Comment, user: user

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :delete_all
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :first_name, :last_name

  has_many :comments
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      render 'posts/show'
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
  end

  def update
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
    if @comment.update(comment_params)
      redirect_to post_path(@post), notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end



  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @post, notice: 'Comment was successfully deleted.'
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!,except: [:index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource


  def index
    @posts = Post.all
  end

  def show
    # @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @user= current_user
    @post.user=@user
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully deleted.'
  end

  private
  def set_post
    @post = Post.find_by(id: params[:id])
    unless @post
      redirect_to posts_url, alert: 'Post not found.'
    end
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Comment</title>
</head>
<body>
<div class="container">
  <h1>New Comment</h1>
  <%= form_with(model: [@post, Comment.new]) do |form| %>
    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content, rows: 3 %>
    </div>
    <div class="actions">
      <%= form.submit 'Add Comment' %>
    </div>
  <% end %>
</div>
</body>
</html>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<%= form_for [@post, @comment] do |form| %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, rows: 3 %>
  </div>
  <div class="actions">
    <%= form.submit 'Edit Comment' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Office</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_importmap_tags %>
  <style>
    .nav a{
        text-decoration: none;
        color: white;
    }
    .hobar a{
        border: none;
        background-color: #942a1d;
        padding: 15px 20px;
        border-radius: 5px;
        border: none;
    }
    .hobar a:hover{
        margin-right: 10px;
        background:blue;
        padding: 15px 20px;
        border-radius: 5px;
        border: none;
        color: white;
    }
    .hobar {
        border: none;
        background: none;
    }
  </style>
</head>
<body>
<nav class="nav">
  <div style="margin-top: 30px;">
    <% if user_signed_in? %>
    <button class="hobar"><%= link_to 'Posts', posts_path %></button>
    <button class="hobar"><%= link_to 'New Post', new_post_path%></button>
    <button class="hobar"><%= link_to 'Logout', destroy_user_session_path, method: :delete %></button>
    <% else %>
      <button class="hobar"><%= link_to 'HOME', root_path%></button>
      <button class="hobar"> <%= link_to 'Login', new_user_session_path %></button>
      <button class="hobar"> <%= link_to 'Register', new_user_registration_path %></button>
    <% end %>
  </div>
</nav>
<main>
  <%= yield %>
</main>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="field">
    <%= f.label :title, class: 'label' %>
    <%= f.text_field :title, class: 'input' %>
  </div>
  <div class="field">
    <%= f.label :content, class: 'label' %>
    <%= f.text_area :content, class: 'textarea' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'button' %>
  </div>
<% end %>

app/views/posts/delete.html.erb
<h1>Delete Post</h1>
<p>Are you sure you want to delete this post?</p>
<%= link_to 'Yes, Delete', post_path(@post), method: :delete, data: { confirm: 'Confirm deletion' }, class: 'btn btn-danger' %>
<%= link_to 'Cancel', posts_path, class: 'btn btn-secondary' %>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit Post</title>
</head>
<body>
<div class="container">
  <h1>Edit Post</h1>
  <%= render 'form' %>
  <div class="links">
    <%= link_to 'Show', @post %> |
    <%= link_to 'Back', posts_path %>
  </div>
</div>
</body>
</html>

app/views/posts/index.html.erb
<h1 style="text-align: center;color: white;background-color: navy">Join Our Community and Share Your Thoughts!</h1>
<p style="font-size: 1em; color: #444"> Welcome to our post and comment website, where your voice matters.
  We believe in the power of meaningful conversations and want to provide
  you with a platform to express your thoughts, share your experiences,
  and engage with a like-minded community. Whether you're a seasoned blogger,
  a passionate hobbyist, or someone who simply wants to connect with others,
  you'll find a place here.</p>
<h2 style="color: #004a80;font-weight: 800;"> POST LIST  </h2>
<style>
    .hop  {
        display: block;
        top: -9px;
        left: 25px;
        background: #ef8023;
        border-radius: 15px;
        color: #fff;
        font-size: 12px;
        line-height: 12px;
        padding: 5px 15px;
        z-index: 9;
    }
    .hop:hover{
        margin-right: 10px;
        background:blue;
        border-radius: 5px;
        border: none;
        color: white;
        padding: 10px 5px;
    }
</style>
<ul>
  <% @posts.each do |post| %>
    <li style="text-decoration: none;color: #2E2F30;font-size: 1.6em">
      <%=post.title%><br/>
      <button class="hop"><%= link_to "OPEN THIS POST",  post_path(post),style: "text-decoration: none;color:white;"%></button>
      <% if can? :edit, post %>
        <button style="background-color: #444444;border-radius: 5px;"><%= link_to 'EDIT', edit_post_path(post),style: "text-decoration: none;color:white;"%></button>
      <% end %>
      <% if can? :destroy, post %>
        <button style="background-color:darkred;border-radius: 5px;"><%= link_to 'Delete', post, data: { turbo_method: :delete, turbo_confirm: "Really?!?" },style: "text-decoration: none;color:white;"%></button>
      <% end %>
      <br/>
    </li>
  <% end %>
</ul>
<button class="hop" style="background-color: #004a80"><%= link_to 'CREATE YOUR POST', new_post_path, style:"text-decoration:none;text-align:center;color:White"%></button>
<h3 style="color: #004a80;font-weight: 800;text-align: center;font-size: 1.6em">Why Choose Us?</h3>
<p style="font-size: 1em; color: #444"><span style="font-size: 1.2em;color: black">Diverse Topics:</span> Our platform covers a wide range of topics, from technology and travel to food and fashion.
  No matter what you're interested in, you're likely to find a discussion that piques your curiosity.</p>
<p style="font-size: 1em; color: #444"><span style="font-size: 1.2em;color: black">User-Friendly Interface: </span>We've designed our website to be user-friendly and intuitive.
  You can easily create posts, add comments, and engage in discussions without any hassle.</p>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Post</title>
</head>
<body>
<div class="container">
  <h1>New Post</h1>
  <%= render 'form' %>
  <div class="links">
    <%= link_to 'Back', posts_path %>
  </div>
</div>
</body>
</html>

app/views/posts/show.html.erb
<h1><%=@post.title %></h1>
<p><%=@post.content %></p>
<p><%=@post.user.email%></p>

<h2>Comments</h2>
<ul>
  <% @comments.each do |comment| %>
    <>
      <%= comment.user.email %>
    <br/>
      <%= comment.content %>
      <% if can? :edit, comment %>
        <%= link_to 'Edit', edit_post_comment_path(@post, comment) %>
    <% end %>
      <% if can? :destroy, comment %>
        <%= link_to 'Delete', post_comment_path(@post, comment), data: { turbo_method: :delete, turbo_confirm: "Really?!?" } %>
      <% end %>
    <br/>
    <br/>
  <% end %>
</ul>

<% if user_signed_in? %>
  <%= render 'comments/form' %>
<% else %>
  <p class="not-signed-in-message">Please <%= link_to 'sign in', new_user_session_path %> or <%= link_to 'register', new_user_registration_path %> to comment on this post.</p>
<% end %>